services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: waterpolo
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: mypass
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin"]
      interval: 5s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile.test
    image: backend:ci
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"

volumes:
  db_data:
