version: "3.9"

services:
  db:
    image: postgres
    env_file:
      - .env.prod
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: always

  backend:
    build: ./backend
    env_file:
      - .env.prod # cambiar a .dev para desarrollo
    expose:
      - "8000"  # solo visible para nginx, no al exterior
    depends_on:
      - db
    restart: always

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - certs:/etc/letsencrypt
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
    restart: always

volumes:
  db_data:
  certs:

