FROM python:3.11-slim

WORKDIR /app

# Instalar dependencias
COPY backend/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
RUN pip install pytest pip-audit

# Copiar la app y los tests
COPY backend /app/backend
COPY tests /app/tests

# Habilitar imports absolutos desde raíz
ENV PYTHONPATH=/app

# Comando por defecto para correr tests
CMD ["pytest", "--maxfail=5", "--disable-warnings"]
