name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      POSTGRES_DB: waterpolo
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: mypass
      DB_HOST: localhost  

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create .env file for CI
        run: |
          echo "POSTGRES_DB=${POSTGRES_DB}" > .env
          echo "POSTGRES_USER=${POSTGRES_USER}" >> .env
          echo "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}" >> .env
          echo "DB_HOST=${DB_HOST}" >> .env

      - name: Start containers
        run: docker compose -f docker-compose.yml up -d --build

      - name: Wait for PostgreSQL
        run: |
          for i in {1..10}; do
            docker compose exec -T db pg_isready && echo "Postgres is ready." && break
            echo "Waiting for postgres..."
            sleep 3
          done

      - name: Install dependencies for host
        run: pip install bandit

      - name: Run static analysis (Bandit)
        run: bandit -r backend -ll

      - name: Run backend tests
        run: |
          docker compose exec -T backend pytest --maxfail=5 --disable-warnings

      - name: Run pip-audit
        run: docker compose exec -T backend pip-audit

      - name: Scan Docker image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: backend
