name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:latest
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
          POSTGRES_DB: mydatabase
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U user -d mydatabase"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt

      - name: Wait for PostgreSQL to be ready
        run: |
          until pg_isready -h db -p 5432; do
            echo "Esperando a PostgreSQL..."
            sleep 2
          done
        env:
          PGHOST: db
          PGUSER: user
          PGPASSWORD: password
          PGDATABASE: mydatabase

      - name: Run tests
        run: |
          pytest --maxfail=5 --disable-warnings

      - name: Security audit with pip-audit
        run: pip-audit

      - name: Build Docker image
        run: docker build -t waterpolo-api:latest ./backend

      - name: Scan Docker image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: waterpolo-api:latest

      - name: Push Docker image to GitHub Container Registry (optional)
        if: github.event_name == 'push'
        run: |
          echo "Skipping push for now"
          # docker tag waterpolo-api:latest ghcr.io/your-username/waterpolo-api:latest
          # echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          # docker push ghcr.io/your-username/waterpolo-api:latest
