name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypass
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Launch containers
        run: docker compose -f docker-compose.yml up -d --build

      - name: Wait for backend
        run: |
          echo "Esperando a backend en http://localhost..."
          for i in {1..10}; do
            if curl -s http://localhost | grep "Welcome"; then
              echo "Backend listo."
              break
            else
              echo "Esperando..."
              sleep 5
            fi
          done

      - name: Run backend tests
        run: docker-compose exec -T backend pytest --maxfail=5 --disable-warnings

      - name: Security audit
        run: docker-compose exec -T backend pip-audit

      - name: Scan Docker image
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: backend
